export const fixtureCases = [
  'ready',
  'duplicate',
  'invalid-url',
  'video-unavailable',
  'transcript-unavailable',
  'provider-outage',
  'reanalysis',
  'pipeline-queued',
  'pipeline-validating',
  'pipeline-transcript',
  'pipeline-structuring',
  'pipeline-artifacts',
  'pipeline-partial',
  'pipeline-failed',
  'pipeline-retrying',
  'pipeline-complete',
  'result-complete',
  'result-legacy',
  'result-partial',
  'result-corrupted',
  'result-empty',
  'result-den-25',
  'result-den-25-partial',
  'result-den-25-public',
] as const;
